### ISSUE TITLE
Commandline Usage

### ISSUE THREAD

**Issue by j538** [sanderjo/GPIO-counter#1]
When I try to use it from the command line and put in 
$ sudo /home/pi/git/gpio-counter.py 23 /var/log/gpio23-counter.log debug
which is the command that you said to use. I get the error 
sudo: /home/pi/git/gpio-counter.py: command not found
Is there another command I should be using?

**Comment by sanderjo** [comment]
You probably did the git clone somewhere else than in /home/pi/git/  ?

**Comment by j538** [comment]
Yep my bad, the clone was inside of another folder
